language: python
sudo: false
python:
  - 3.4
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda install --yes pip python==$TRAVIS_PYTHON_VERSION numpy matplotlib
  - pip install flit
install:
  - flit install --env -s
script:
  - py.test --cov plotchecker
after_success:
  - codecov
